server:
  port: 8080

spring:
  application:
    name: gblog-api
  profiles:
    active: prod
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

feign:
  client:
    config:
      #default代表所有服务
      default:
        #feign客户端建立连接超时时间
        connect-timeout: 30000
        #feign客户端建立连接后读取资源超时时间
        read-timeout: 60000
      #而service-test表示当调用service-test这个服务时，用下面的配置
      service-test:
        connect-timeout: 10000
        read-timeout: 20000

# 日志配置
logging:
  level:
    com.zhloong: debug
    org.springframework: warn